apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-2

vpc:
  id: vpc-0f2fd21c9ee5b09e1
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-2a:
        id: subnet-0d9bf739e7629fb3c
      us-east-2b:
        id: subnet-07b3774b74c33698e
    # private:
    #   ap-southeast-1a:
    #     id: subnet-083e6c24a30ae4ed2
    #   ap-southeast-1b:
    #     id: subnet-083e6c24a30ae4ed2

# nodeGroups:
#   - name: EKS-public-workers
#     instanceType: t2.medium
#     desiredCapacity: 2
#   - name: EKS-private-workers
#     instanceType: t2.medium
#     desiredCapacity: 1
#     privateNetworking: true